name: CI/CD for Online Book Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.2.0'

      - name: Install dependencies
        run: npm install

      - name: Replace the config settings
        run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js

      - name: Start BackEnd
        run: npm run server &
      
      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Start FrontEnd
        run: npm run start &
      
      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run tests with Playwright
        run: npm run test
  deploy-be:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build_and_test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_BE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
  deploy-fe:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: deploy-be
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_FE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
